# Railway Nixpacks Configuration for AI Dock
# This tells Railway how to build and run your FastAPI backend

[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "npm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "cd Back && pip install -r requirements.txt",
    "cd Front && npm ci"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "cd Front && npm run build",
    "mkdir -p Back/static",
    "cp -r Front/dist/* Back/static/ || echo 'Frontend build not found, continuing...'"
]

[start]
cmd = "cd Back && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "Back"
NODE_ENV = "production"
