providers = ["python"]

[variables]
PYTHONPATH = "/app/Back"
DATABASE_URL = "sqlite:///./ai_dock_dev.db"
SECRET_KEY = "temp-railway-deployment-key-replace-in-production"
ENVIRONMENT = "development"
DEBUG = "true"

[phases.install]
cmd = "cd Back && pip install -r requirements.txt"

[phases.build]
cmd = "echo 'No build step needed for FastAPI'"

[start]
cmd = "cd Back && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
