providers = ["python"]

[variables]
PYTHONPATH = "/app/Back"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmd = "cd Back && pip install -r requirements.txt"

[phases.build]
cmd = "echo 'Skipping frontend build - backend only deployment'"

[start]
cmd = "cd Back && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
