[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python FastAPI backend ready'"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
